# appveyor nightly file
# http://www.appveyor.com/docs/appveyor-yml

version: 1.3.0.{build}

# # http://www.appveyor.com/docs/build-cache#caching-chocolatey-packages
# cache:
#   - C:\ProgramData\chocolatey\bin -> appveyor.yml
#   - C:\ProgramData\chocolatey\lib -> appveyor.yml
    
environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  matrix:
  - VS_GEN: Visual Studio 14 2015
    CONFIG: Release
    B_NAME: Windows-x86
    platform: x86
    configuration: Release
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0
  - VS_GEN: Visual Studio 14 2015 Win64
    CONFIG: Release
    B_NAME: Windows-x86_64
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0
    platform: x64
    configuration: Release

# scripts that are called at very beginning, before repo cloning
init:
  # Print environment info ( set / systeminfo)
  - msbuild /version
  - cmake --version
  - python --version
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - choco install activetcl
  - choco install pandoc
  
before_build:
  - cmake -Wno-dev -G"%VS_GEN%" -DCMAKE_BUILD_TYPE=%CONFIG% -DVERA_USE_SYSTEM_LUA=OFF -DBUILDNAME="%B_NAME%"
  - ctest -D NightlyStart -C %CONFIG%
 
# to run your custom scripts instead of automatic MSBuild
build_script:
# Do not run Test=Update/Configure, only Start/Build/Test/Submit (TODO: Coverage)
  - ctest -D NightlyBuild -j %NUMBER_OF_PROCESSORS% -C %CONFIG%

# to run your custom scripts instead of automatic tests
test_script:
  - ctest -D NightlyTest -j %NUMBER_OF_PROCESSORS% -C %CONFIG% || true
  - ctest -D NightlySubmit -C %CONFIG%

# Uncomment below if you want to debug via RDP
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
